// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/profile/service.proto

package github_com_protorepo_profile_go

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protobuf "github.com/oojob/protobuf"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

/// ProfileSecurity account_type :- weather the account belong's to job
/// provide or job seeker
type ProfileSecurity_AccountType int32

const (
	ProfileSecurity_BASE    ProfileSecurity_AccountType = 0
	ProfileSecurity_COMPANY ProfileSecurity_AccountType = 1
	ProfileSecurity_FUNDING ProfileSecurity_AccountType = 2
	ProfileSecurity_JOB     ProfileSecurity_AccountType = 3
)

var ProfileSecurity_AccountType_name = map[int32]string{
	0: "BASE",
	1: "COMPANY",
	2: "FUNDING",
	3: "JOB",
}

var ProfileSecurity_AccountType_value = map[string]int32{
	"BASE":    0,
	"COMPANY": 1,
	"FUNDING": 2,
	"JOB":     3,
}

func (x ProfileSecurity_AccountType) String() string {
	return proto.EnumName(ProfileSecurity_AccountType_name, int32(x))
}

func (ProfileSecurity_AccountType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b18d8e3cf7cb2b0f, []int{1, 0}
}

//*
// Education help's us to identify the data and also weather or not we need to
// show it on the public profile"
type Education struct {
	/// Education education :- school/college name which should be your primary
	/// education
	Education string `protobuf:"bytes,1,opt,name=education,proto3" json:"education,omitempty"`
	/// Education show :- weather or not you want to show the education on public
	Show                 bool     `protobuf:"varint,2,opt,name=show,proto3" json:"show,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Education) Reset()         { *m = Education{} }
func (m *Education) String() string { return proto.CompactTextString(m) }
func (*Education) ProtoMessage()    {}
func (*Education) Descriptor() ([]byte, []int) {
	return fileDescriptor_b18d8e3cf7cb2b0f, []int{0}
}

func (m *Education) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Education.Unmarshal(m, b)
}
func (m *Education) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Education.Marshal(b, m, deterministic)
}
func (m *Education) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Education.Merge(m, src)
}
func (m *Education) XXX_Size() int {
	return xxx_messageInfo_Education.Size(m)
}
func (m *Education) XXX_DiscardUnknown() {
	xxx_messageInfo_Education.DiscardUnknown(m)
}

var xxx_messageInfo_Education proto.InternalMessageInfo

func (m *Education) GetEducation() string {
	if m != nil {
		return m.Education
	}
	return ""
}

func (m *Education) GetShow() bool {
	if m != nil {
		return m.Show
	}
	return false
}

//*
// ProfileSecurity help's us to maintain data related to profile security
// aspects
type ProfileSecurity struct {
	/// ProfileSecurity password :- help's us to store encrypted password
	Password string `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	/// ProfileSecurity password_salt :- help's us to store password salt round
	/// it will help us in long term when migrating to other auth providers
	PasswordSalt string `protobuf:"bytes,2,opt,name=password_salt,json=passwordSalt,proto3" json:"password_salt,omitempty"`
	/// ProfileSecurity password_hash :- secret used for password hash
	/// still working on it
	PasswordHash string `protobuf:"bytes,3,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	/// ProfileSecurity code :- security code based on ccurrenccct usuage
	/// For ex: for password reset, we will use to set code for password reset
	Code string `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	/// ProfileSecurity code_type :- the code geneated above will give meaning
	/// that how that generated peice of ode should be used
	CodeType    string                      `protobuf:"bytes,5,opt,name=code_type,json=codeType,proto3" json:"code_type,omitempty"`
	AccountType ProfileSecurity_AccountType `protobuf:"varint,6,opt,name=account_type,json=accountType,proto3,enum=profile.ProfileSecurity_AccountType" json:"account_type,omitempty"`
	/// ProfileSecurity verified :- weather the profile is verified or nots
	Verified             bool     `protobuf:"varint,7,opt,name=verified,proto3" json:"verified,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileSecurity) Reset()         { *m = ProfileSecurity{} }
func (m *ProfileSecurity) String() string { return proto.CompactTextString(m) }
func (*ProfileSecurity) ProtoMessage()    {}
func (*ProfileSecurity) Descriptor() ([]byte, []int) {
	return fileDescriptor_b18d8e3cf7cb2b0f, []int{1}
}

func (m *ProfileSecurity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileSecurity.Unmarshal(m, b)
}
func (m *ProfileSecurity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileSecurity.Marshal(b, m, deterministic)
}
func (m *ProfileSecurity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileSecurity.Merge(m, src)
}
func (m *ProfileSecurity) XXX_Size() int {
	return xxx_messageInfo_ProfileSecurity.Size(m)
}
func (m *ProfileSecurity) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileSecurity.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileSecurity proto.InternalMessageInfo

func (m *ProfileSecurity) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *ProfileSecurity) GetPasswordSalt() string {
	if m != nil {
		return m.PasswordSalt
	}
	return ""
}

func (m *ProfileSecurity) GetPasswordHash() string {
	if m != nil {
		return m.PasswordHash
	}
	return ""
}

func (m *ProfileSecurity) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ProfileSecurity) GetCodeType() string {
	if m != nil {
		return m.CodeType
	}
	return ""
}

func (m *ProfileSecurity) GetAccountType() ProfileSecurity_AccountType {
	if m != nil {
		return m.AccountType
	}
	return ProfileSecurity_BASE
}

func (m *ProfileSecurity) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

//*
// Profile help's us to store one's profile.
// it will help us to identify the base entity and it act's as a base connector
// for different domain.
type Profile struct {
	/// profile :- mongodb generated ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	/// Profile identifier :- base iddentifier act's as unique identifier
	Identity *protobuf.Identifier `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	/// Profile given_name :- act's as first name
	GivenName string `protobuf:"bytes,3,opt,name=given_name,json=givenName,proto3" json:"given_name,omitempty"`
	/// Profile middle_name :- user's middlename and it's optional
	MiddleName string `protobuf:"bytes,4,opt,name=middle_name,json=middleName,proto3" json:"middle_name,omitempty"`
	/// Profile family_name :- last name or sirname
	FamilyName string `protobuf:"bytes,5,opt,name=family_name,json=familyName,proto3" json:"family_name,omitempty"`
	/// Profile username :- it should be unique and it help's us
	/// to identify uniquely
	Username string `protobuf:"bytes,6,opt,name=username,proto3" json:"username,omitempty"`
	/// Profile email :- email address of the user
	Email *protobuf.Email `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	/// Profile gender :- it should be based on choice
	Gender string `protobuf:"bytes,8,opt,name=gender,proto3" json:"gender,omitempty"`
	/// Profile birthdate :- user's birthdate
	Birthdate *timestamp.Timestamp `protobuf:"bytes,9,opt,name=birthdate,proto3" json:"birthdate,omitempty"`
	/// Profile current_position :- where he works and at what position
	CurrentPosition string `protobuf:"bytes,10,opt,name=current_position,json=currentPosition,proto3" json:"current_position,omitempty"`
	/// Profile education :- primary education
	Education *Education `protobuf:"bytes,11,opt,name=education,proto3" json:"education,omitempty"`
	/// Profile address :- address of the preferred user
	Address *protobuf.Address `protobuf:"bytes,12,opt,name=address,proto3" json:"address,omitempty"`
	/// ProfileSecurity help's us to maintain data related to profile security
	Security *ProfileSecurity `protobuf:"bytes,13,opt,name=security,proto3" json:"security,omitempty"`
	/// Profile metadata :- metadata related to the user
	Metadata             *protobuf.Metadata `protobuf:"bytes,14,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_b18d8e3cf7cb2b0f, []int{2}
}

func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (m *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(m, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Profile) GetIdentity() *protobuf.Identifier {
	if m != nil {
		return m.Identity
	}
	return nil
}

func (m *Profile) GetGivenName() string {
	if m != nil {
		return m.GivenName
	}
	return ""
}

func (m *Profile) GetMiddleName() string {
	if m != nil {
		return m.MiddleName
	}
	return ""
}

func (m *Profile) GetFamilyName() string {
	if m != nil {
		return m.FamilyName
	}
	return ""
}

func (m *Profile) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Profile) GetEmail() *protobuf.Email {
	if m != nil {
		return m.Email
	}
	return nil
}

func (m *Profile) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *Profile) GetBirthdate() *timestamp.Timestamp {
	if m != nil {
		return m.Birthdate
	}
	return nil
}

func (m *Profile) GetCurrentPosition() string {
	if m != nil {
		return m.CurrentPosition
	}
	return ""
}

func (m *Profile) GetEducation() *Education {
	if m != nil {
		return m.Education
	}
	return nil
}

func (m *Profile) GetAddress() *protobuf.Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Profile) GetSecurity() *ProfileSecurity {
	if m != nil {
		return m.Security
	}
	return nil
}

func (m *Profile) GetMetadata() *protobuf.Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

//*
// ConfirmProfileRequest :- request object for confirming profile
// either username/email has to be filled for confirmation
type ConfirmProfileRequest struct {
	/// ConfirmProfileRequest username :- help's us to idenity
	/// whose profile we need to confirm
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	/// ConfirmProfileRequest email :- help's us to idenity
	/// whose profile we need to confirm
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	/// ConfirmProfileRequest token :- help's us to idenity whose profile
	/// we need to confirm with the help of passed token
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmProfileRequest) Reset()         { *m = ConfirmProfileRequest{} }
func (m *ConfirmProfileRequest) String() string { return proto.CompactTextString(m) }
func (*ConfirmProfileRequest) ProtoMessage()    {}
func (*ConfirmProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b18d8e3cf7cb2b0f, []int{3}
}

func (m *ConfirmProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmProfileRequest.Unmarshal(m, b)
}
func (m *ConfirmProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmProfileRequest.Marshal(b, m, deterministic)
}
func (m *ConfirmProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmProfileRequest.Merge(m, src)
}
func (m *ConfirmProfileRequest) XXX_Size() int {
	return xxx_messageInfo_ConfirmProfileRequest.Size(m)
}
func (m *ConfirmProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmProfileRequest proto.InternalMessageInfo

func (m *ConfirmProfileRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ConfirmProfileRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ConfirmProfileRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

//*
// ReadProfileRequest help's to to pass profile ID whose profile data we are
// required to ask
type ReadProfileRequest struct {
	/// ReadProfileRequest account_id :- preferred account id
	/// whose data we need to search
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadProfileRequest) Reset()         { *m = ReadProfileRequest{} }
func (m *ReadProfileRequest) String() string { return proto.CompactTextString(m) }
func (*ReadProfileRequest) ProtoMessage()    {}
func (*ReadProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b18d8e3cf7cb2b0f, []int{4}
}

func (m *ReadProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadProfileRequest.Unmarshal(m, b)
}
func (m *ReadProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadProfileRequest.Marshal(b, m, deterministic)
}
func (m *ReadProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadProfileRequest.Merge(m, src)
}
func (m *ReadProfileRequest) XXX_Size() int {
	return xxx_messageInfo_ReadProfileRequest.Size(m)
}
func (m *ReadProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadProfileRequest proto.InternalMessageInfo

func (m *ReadProfileRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

//*
// ValidateUsernameRequest :- username validation request
type ValidateUsernameRequest struct {
	/// ValidateUsernameRequest username :- username which we want to validate
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateUsernameRequest) Reset()         { *m = ValidateUsernameRequest{} }
func (m *ValidateUsernameRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateUsernameRequest) ProtoMessage()    {}
func (*ValidateUsernameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b18d8e3cf7cb2b0f, []int{5}
}

func (m *ValidateUsernameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateUsernameRequest.Unmarshal(m, b)
}
func (m *ValidateUsernameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateUsernameRequest.Marshal(b, m, deterministic)
}
func (m *ValidateUsernameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateUsernameRequest.Merge(m, src)
}
func (m *ValidateUsernameRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateUsernameRequest.Size(m)
}
func (m *ValidateUsernameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateUsernameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateUsernameRequest proto.InternalMessageInfo

func (m *ValidateUsernameRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

//*
// ValidateEmailRequest :- email validation request
type ValidateEmailRequest struct {
	/// ValidateEmailRequest email :- email which we want to validate
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateEmailRequest) Reset()         { *m = ValidateEmailRequest{} }
func (m *ValidateEmailRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateEmailRequest) ProtoMessage()    {}
func (*ValidateEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b18d8e3cf7cb2b0f, []int{6}
}

func (m *ValidateEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateEmailRequest.Unmarshal(m, b)
}
func (m *ValidateEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateEmailRequest.Marshal(b, m, deterministic)
}
func (m *ValidateEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateEmailRequest.Merge(m, src)
}
func (m *ValidateEmailRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateEmailRequest.Size(m)
}
func (m *ValidateEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateEmailRequest proto.InternalMessageInfo

func (m *ValidateEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

//*
// AuthReq :- authentication request
type AuthRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b18d8e3cf7cb2b0f, []int{7}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuthRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

//*
// AuthRes :- authentication response
type AuthResponse struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	Valid                bool     `protobuf:"varint,3,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b18d8e3cf7cb2b0f, []int{8}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *AuthResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *AuthResponse) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

//*
// AccessDetails :- auth data response
type AccessDetails struct {
	Authorized           bool     `protobuf:"varint,1,opt,name=authorized,proto3" json:"authorized,omitempty"`
	AccessUuid           string   `protobuf:"bytes,2,opt,name=access_uuid,json=accessUuid,proto3" json:"access_uuid,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	UserId               string   `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Identifier           string   `protobuf:"bytes,6,opt,name=identifier,proto3" json:"identifier,omitempty"`
	AccountType          string   `protobuf:"bytes,7,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	Verified             bool     `protobuf:"varint,8,opt,name=verified,proto3" json:"verified,omitempty"`
	Exp                  int64    `protobuf:"varint,9,opt,name=exp,proto3" json:"exp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccessDetails) Reset()         { *m = AccessDetails{} }
func (m *AccessDetails) String() string { return proto.CompactTextString(m) }
func (*AccessDetails) ProtoMessage()    {}
func (*AccessDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_b18d8e3cf7cb2b0f, []int{9}
}

func (m *AccessDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessDetails.Unmarshal(m, b)
}
func (m *AccessDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessDetails.Marshal(b, m, deterministic)
}
func (m *AccessDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessDetails.Merge(m, src)
}
func (m *AccessDetails) XXX_Size() int {
	return xxx_messageInfo_AccessDetails.Size(m)
}
func (m *AccessDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessDetails.DiscardUnknown(m)
}

var xxx_messageInfo_AccessDetails proto.InternalMessageInfo

func (m *AccessDetails) GetAuthorized() bool {
	if m != nil {
		return m.Authorized
	}
	return false
}

func (m *AccessDetails) GetAccessUuid() string {
	if m != nil {
		return m.AccessUuid
	}
	return ""
}

func (m *AccessDetails) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AccessDetails) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AccessDetails) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AccessDetails) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *AccessDetails) GetAccountType() string {
	if m != nil {
		return m.AccountType
	}
	return ""
}

func (m *AccessDetails) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

func (m *AccessDetails) GetExp() int64 {
	if m != nil {
		return m.Exp
	}
	return 0
}

//*
// TokenRequest :- passing token for getting data
type TokenRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	AccessUuid           string   `protobuf:"bytes,2,opt,name=access_uuid,json=accessUuid,proto3" json:"access_uuid,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenRequest) Reset()         { *m = TokenRequest{} }
func (m *TokenRequest) String() string { return proto.CompactTextString(m) }
func (*TokenRequest) ProtoMessage()    {}
func (*TokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b18d8e3cf7cb2b0f, []int{10}
}

func (m *TokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenRequest.Unmarshal(m, b)
}
func (m *TokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenRequest.Marshal(b, m, deterministic)
}
func (m *TokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenRequest.Merge(m, src)
}
func (m *TokenRequest) XXX_Size() int {
	return xxx_messageInfo_TokenRequest.Size(m)
}
func (m *TokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TokenRequest proto.InternalMessageInfo

func (m *TokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *TokenRequest) GetAccessUuid() string {
	if m != nil {
		return m.AccessUuid
	}
	return ""
}

func (m *TokenRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func init() {
	proto.RegisterEnum("profile.ProfileSecurity_AccountType", ProfileSecurity_AccountType_name, ProfileSecurity_AccountType_value)
	proto.RegisterType((*Education)(nil), "profile.Education")
	proto.RegisterType((*ProfileSecurity)(nil), "profile.ProfileSecurity")
	proto.RegisterType((*Profile)(nil), "profile.Profile")
	proto.RegisterType((*ConfirmProfileRequest)(nil), "profile.ConfirmProfileRequest")
	proto.RegisterType((*ReadProfileRequest)(nil), "profile.ReadProfileRequest")
	proto.RegisterType((*ValidateUsernameRequest)(nil), "profile.ValidateUsernameRequest")
	proto.RegisterType((*ValidateEmailRequest)(nil), "profile.ValidateEmailRequest")
	proto.RegisterType((*AuthRequest)(nil), "profile.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "profile.AuthResponse")
	proto.RegisterType((*AccessDetails)(nil), "profile.AccessDetails")
	proto.RegisterType((*TokenRequest)(nil), "profile.TokenRequest")
}

func init() {
	proto.RegisterFile("services/profile/service.proto", fileDescriptor_b18d8e3cf7cb2b0f)
}

var fileDescriptor_b18d8e3cf7cb2b0f = []byte{
	// 1108 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x6d, 0x6f, 0x1b, 0x45,
	0x10, 0xc6, 0xef, 0xf6, 0xd8, 0x49, 0xad, 0x55, 0xda, 0x9e, 0x5c, 0xf2, 0xd2, 0x2b, 0x45, 0x01,
	0x11, 0xa7, 0x4a, 0x00, 0x21, 0x14, 0x04, 0xce, 0x0b, 0x6d, 0x80, 0xa6, 0xd1, 0x25, 0x29, 0xa2,
	0x42, 0x98, 0x8d, 0x6f, 0xec, 0x5b, 0x7a, 0xf6, 0x1e, 0xb7, 0x7b, 0x29, 0xe6, 0x37, 0xf0, 0x9b,
	0xf8, 0xce, 0x0f, 0xe2, 0x3b, 0xba, 0xdd, 0xbd, 0xf3, 0xd9, 0xa9, 0x4d, 0x22, 0xc4, 0xa7, 0xdc,
	0xcc, 0x3e, 0x33, 0x3b, 0xf3, 0xcc, 0xec, 0x13, 0xc3, 0x9a, 0xc0, 0xf0, 0x8a, 0xf5, 0x50, 0x6c,
	0x07, 0x21, 0xef, 0x33, 0x1f, 0xb7, 0x8d, 0xa3, 0x1d, 0x84, 0x5c, 0x72, 0x52, 0x31, 0xee, 0xd6,
	0xfb, 0x03, 0x26, 0xbd, 0xe8, 0xb2, 0xdd, 0xe3, 0xc3, 0x6d, 0xce, 0x7f, 0xe1, 0x97, 0xdb, 0x0a,
	0x70, 0x19, 0xf5, 0xb7, 0xc5, 0x58, 0x48, 0x1c, 0xea, 0x80, 0xd6, 0xe6, 0x7c, 0xdc, 0x10, 0x25,
	0x75, 0xa9, 0xa4, 0x06, 0xf9, 0x78, 0x3e, 0x32, 0xf0, 0x69, 0x52, 0xc1, 0xa2, 0x8b, 0x3d, 0xa4,
	0xbe, 0xf4, 0x0c, 0x6e, 0x7d, 0xc0, 0xf9, 0xc0, 0xc7, 0xc9, 0xa9, 0x64, 0x43, 0x14, 0x92, 0x0e,
	0x03, 0x0d, 0xb0, 0xbf, 0x80, 0xda, 0x91, 0x1b, 0xf5, 0xa8, 0x64, 0x7c, 0x44, 0xde, 0x85, 0x1a,
	0x26, 0x86, 0x95, 0xdb, 0xc8, 0x6d, 0xd6, 0x9c, 0x89, 0x83, 0x10, 0x28, 0x0a, 0x8f, 0xbf, 0xb1,
	0xf2, 0x1b, 0xb9, 0xcd, 0xaa, 0xa3, 0xbe, 0xed, 0xbf, 0xf2, 0x70, 0xe7, 0x54, 0x93, 0x71, 0x86,
	0xbd, 0x28, 0x64, 0x72, 0x4c, 0x5a, 0x50, 0x0d, 0xa8, 0x10, 0x6f, 0x78, 0xe8, 0x9a, 0x24, 0xa9,
	0x4d, 0x1e, 0xc1, 0x52, 0xf2, 0xdd, 0x15, 0xd4, 0x97, 0x2a, 0x59, 0xcd, 0x69, 0x24, 0xce, 0x33,
	0xea, 0xcb, 0x29, 0x90, 0x47, 0x85, 0x67, 0x15, 0xa6, 0x41, 0xcf, 0xa8, 0xf0, 0xe2, 0x6a, 0x7a,
	0xdc, 0x45, 0xab, 0xa8, 0xce, 0xd4, 0x37, 0x79, 0x00, 0xb5, 0xf8, 0x6f, 0x57, 0x8e, 0x03, 0xb4,
	0x4a, 0xfa, 0xea, 0xd8, 0x71, 0x3e, 0x0e, 0x90, 0x3c, 0x85, 0x06, 0xed, 0xf5, 0x78, 0x34, 0x92,
	0xfa, 0xbc, 0xbc, 0x91, 0xdb, 0x5c, 0xde, 0x79, 0xaf, 0x6d, 0x66, 0xd9, 0x9e, 0x69, 0xa3, 0xdd,
	0xd1, 0xe0, 0x38, 0xd6, 0xa9, 0xd3, 0x89, 0x11, 0xf7, 0x77, 0x85, 0x21, 0xeb, 0x33, 0x74, 0xad,
	0x8a, 0xe2, 0x22, 0xb5, 0xed, 0xcf, 0xa1, 0x9e, 0x89, 0x23, 0x55, 0x28, 0xee, 0x77, 0xce, 0x8e,
	0x9a, 0xef, 0x90, 0x3a, 0x54, 0x0e, 0x5e, 0x3c, 0x3f, 0xed, 0x9c, 0xfc, 0xd0, 0xcc, 0xc5, 0xc6,
	0xd7, 0x17, 0x27, 0x87, 0xc7, 0x27, 0x4f, 0x9b, 0x79, 0x52, 0x81, 0xc2, 0x37, 0x2f, 0xf6, 0x9b,
	0x05, 0xfb, 0xef, 0x22, 0x54, 0x4c, 0x11, 0x64, 0x19, 0xf2, 0x2c, 0x61, 0x2f, 0xcf, 0x5c, 0xd2,
	0x81, 0x2a, 0x73, 0x71, 0x24, 0x99, 0x1c, 0x2b, 0xca, 0xea, 0x3b, 0x8f, 0xdb, 0x93, 0x15, 0x68,
	0xab, 0x15, 0x68, 0x27, 0x43, 0x6e, 0x1f, 0x2b, 0x68, 0x9f, 0x61, 0xe8, 0xa4, 0x61, 0x64, 0x15,
	0x60, 0xc0, 0xae, 0x70, 0xd4, 0x1d, 0xd1, 0x21, 0x1a, 0x4a, 0x6b, 0xca, 0x73, 0x42, 0x87, 0x48,
	0xd6, 0xa1, 0x3e, 0x64, 0xae, 0xeb, 0xa3, 0x3e, 0xd7, 0xb4, 0x82, 0x76, 0x25, 0x80, 0x3e, 0x1d,
	0x32, 0x7f, 0xac, 0x01, 0x9a, 0x5e, 0xd0, 0x2e, 0x05, 0x68, 0x41, 0x35, 0x12, 0x18, 0xaa, 0xd3,
	0xb2, 0x26, 0x3f, 0xb1, 0xc9, 0xa7, 0x50, 0xc2, 0x21, 0x65, 0xbe, 0x22, 0xac, 0xbe, 0xb3, 0xb1,
	0xa0, 0xf8, 0xa3, 0x18, 0xe7, 0x68, 0x38, 0xb9, 0x07, 0xe5, 0x01, 0x8e, 0x5c, 0x0c, 0xad, 0xaa,
	0xca, 0x68, 0x2c, 0xf2, 0x19, 0xd4, 0x2e, 0x59, 0x28, 0x3d, 0x97, 0x4a, 0xb4, 0x6a, 0x2a, 0x67,
	0xab, 0xad, 0x77, 0x7d, 0x92, 0xe9, 0x3c, 0xd9, 0x75, 0x67, 0x02, 0x26, 0x1f, 0x40, 0xb3, 0x17,
	0x85, 0x21, 0x8e, 0x64, 0x37, 0xe0, 0x82, 0xa9, 0x55, 0x07, 0x95, 0xfb, 0x8e, 0xf1, 0x9f, 0x1a,
	0x37, 0x79, 0x92, 0x7d, 0x0e, 0x75, 0x75, 0x09, 0x49, 0xd7, 0x25, 0x7d, 0x35, 0xd9, 0x27, 0xb2,
	0x07, 0x15, 0xea, 0xba, 0x21, 0x0a, 0x61, 0x35, 0x14, 0xde, 0x5e, 0xd0, 0x68, 0x47, 0x23, 0x9d,
	0x24, 0x84, 0x7c, 0x0c, 0x55, 0x61, 0xb6, 0xcf, 0x5a, 0x52, 0xe1, 0xd6, 0xbc, 0xed, 0x74, 0x52,
	0x24, 0xf9, 0x12, 0xaa, 0x89, 0x86, 0x58, 0xcb, 0x2a, 0xea, 0xd1, 0x82, 0x4b, 0x9f, 0x1b, 0xa8,
	0x93, 0x06, 0xd9, 0x5d, 0xb8, 0x7b, 0xc0, 0x47, 0x7d, 0x16, 0x0e, 0xcd, 0x25, 0x0e, 0xfe, 0x1a,
	0xa1, 0x90, 0x53, 0x03, 0xcd, 0xcd, 0x0c, 0x74, 0x25, 0x19, 0xa8, 0x7e, 0xc0, 0x66, 0x5c, 0x2b,
	0x50, 0x92, 0xfc, 0x35, 0x8e, 0xcc, 0x7a, 0x69, 0xc3, 0xde, 0x05, 0xe2, 0x20, 0x75, 0x67, 0xb2,
	0xaf, 0x02, 0x24, 0xef, 0x31, 0x5d, 0xf5, 0x9a, 0xf1, 0x1c, 0xbb, 0xf6, 0x27, 0x70, 0xff, 0x25,
	0xf5, 0x59, 0x3c, 0xb3, 0x0b, 0x73, 0xe9, 0x0d, 0xea, 0xb2, 0x3f, 0x82, 0x95, 0x24, 0x4c, 0x2f,
	0x92, 0x89, 0x49, 0xeb, 0xcd, 0x65, 0xea, 0xb5, 0x8f, 0xa0, 0xde, 0x89, 0xa4, 0x77, 0x93, 0x86,
	0xb3, 0xaa, 0x96, 0x9f, 0x56, 0x35, 0xdb, 0x87, 0x86, 0x4e, 0x23, 0x02, 0x3e, 0x12, 0x48, 0x1e,
	0x2a, 0xa9, 0x41, 0x21, 0xba, 0x9a, 0x0d, 0x9d, 0xab, 0xae, 0x7d, 0xe7, 0xb1, 0x2b, 0xd6, 0xb8,
	0x10, 0xfb, 0x21, 0x0a, 0xcf, 0x60, 0x8c, 0x10, 0x1a, 0xa7, 0x06, 0xad, 0x40, 0xe9, 0x2a, 0x6e,
	0x46, 0xd1, 0x59, 0x75, 0xb4, 0x61, 0xff, 0x91, 0x87, 0xa5, 0x8e, 0x4a, 0x75, 0x88, 0x92, 0x32,
	0x5f, 0x90, 0x35, 0x00, 0x1a, 0x49, 0x8f, 0x87, 0xec, 0x77, 0xd4, 0x54, 0x56, 0x9d, 0x8c, 0x27,
	0x7e, 0xba, 0xa6, 0x9e, 0x28, 0x62, 0x49, 0xf9, 0xa0, 0x5d, 0x17, 0x11, 0x73, 0xa7, 0x1a, 0x2f,
	0xcc, 0x9b, 0x74, 0x31, 0x3b, 0xe9, 0xfb, 0x50, 0x89, 0x11, 0xf1, 0xe8, 0xb4, 0x12, 0x94, 0x63,
	0xf3, 0xd8, 0x8d, 0x6b, 0x61, 0xa9, 0xfc, 0x18, 0x1d, 0xc8, 0x78, 0x0c, 0x37, 0x13, 0x19, 0xae,
	0xa4, 0xdc, 0xbc, 0x55, 0x60, 0xab, 0xd3, 0x02, 0x4b, 0x9a, 0x50, 0xc0, 0xdf, 0x02, 0xf5, 0xe4,
	0x0b, 0x4e, 0xfc, 0x69, 0xff, 0x04, 0x0d, 0xc5, 0x56, 0x66, 0xd2, 0x59, 0xd6, 0xb5, 0xf1, 0xef,
	0x14, 0x64, 0x1a, 0x2a, 0x64, 0x1b, 0xda, 0xf9, 0xb3, 0x02, 0xcb, 0xe9, 0xeb, 0x53, 0xbf, 0x02,
	0xc8, 0x2e, 0x14, 0xe3, 0x79, 0x93, 0x95, 0xf4, 0x79, 0x66, 0xb6, 0xa8, 0x75, 0x77, 0xc6, 0x6b,
	0x96, 0x62, 0x0f, 0x1a, 0x4e, 0x76, 0xb8, 0x13, 0x58, 0xb6, 0xfc, 0xf9, 0xd1, 0xf5, 0x97, 0x31,
	0x07, 0xe3, 0x85, 0xc1, 0xf7, 0x26, 0xc1, 0x53, 0x0b, 0xf2, 0x2d, 0x94, 0xbf, 0xe3, 0x03, 0x1e,
	0xc9, 0x79, 0x81, 0x1f, 0x2e, 0x90, 0x8c, 0x43, 0xec, 0xd3, 0xc8, 0x97, 0x69, 0x29, 0x5f, 0xc1,
	0xd2, 0x41, 0x88, 0x54, 0x62, 0xf2, 0xcf, 0xaa, 0x39, 0xab, 0x52, 0xad, 0xd5, 0x85, 0xff, 0x9c,
	0xc8, 0x8f, 0xb0, 0x3c, 0xad, 0x38, 0x64, 0x2d, 0x4d, 0xf1, 0x56, 0x29, 0xba, 0x55, 0x7d, 0x7b,
	0x50, 0xcf, 0xc8, 0x0d, 0x79, 0x90, 0xa6, 0xbe, 0x2e, 0x42, 0xad, 0x6b, 0xa5, 0xc7, 0xdd, 0x5d,
	0x04, 0xee, 0x7f, 0xe9, 0xee, 0x67, 0x68, 0xce, 0x2a, 0x17, 0xd9, 0x48, 0x93, 0xcc, 0x11, 0xb5,
	0x5b, 0x75, 0xf8, 0x0a, 0x96, 0xa6, 0x44, 0x8e, 0xac, 0x5e, 0x4b, 0x9f, 0x15, 0xbf, 0x5b, 0xe5,
	0xee, 0x43, 0xe9, 0xc0, 0xc3, 0xde, 0x6b, 0xb2, 0xb5, 0x20, 0xe8, 0x99, 0xfa, 0x8d, 0xa9, 0x70,
	0xc9, 0x1d, 0xed, 0x9b, 0xc2, 0xcd, 0x3d, 0x1e, 0x94, 0xbe, 0xa7, 0xb2, 0xe7, 0xfd, 0xcf, 0xf7,
	0x3c, 0xc9, 0xed, 0x3f, 0x7c, 0xb5, 0x9e, 0x09, 0x51, 0xe0, 0x10, 0x03, 0xbe, 0x65, 0x28, 0xdb,
	0x1a, 0xf0, 0xcb, 0xb2, 0xf2, 0xee, 0xfe, 0x13, 0x00, 0x00, 0xff, 0xff, 0x73, 0xce, 0x28, 0x01,
	0xf9, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProfileServiceClient is the client API for ProfileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProfileServiceClient interface {
	/// ProfileService Auth for authentication
	Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	/// ProfileService RefreshToken for fetching new refresh token
	RefreshToken(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	/// ProfileService VerifyToken help's us to verify the auth token and return
	/// us back the profile data
	VerifyToken(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*AccessDetails, error)
	/// ProfileService Logout help's us to remove all the data associated with the
	/// user session
	Logout(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*protobuf.DefaultResponse, error)
	/// ProfileService CreateProfile :- help's uo to create a profile
	CreateProfile(ctx context.Context, in *Profile, opts ...grpc.CallOption) (*protobuf.Id, error)
	/// ProfileService ConfirmProfile :- help's us to verify the profile
	ConfirmProfile(ctx context.Context, in *ConfirmProfileRequest, opts ...grpc.CallOption) (*protobuf.DefaultResponse, error)
	/// ProfileService ReadProfile :- help's us to read the entire profile data
	ReadProfile(ctx context.Context, in *ReadProfileRequest, opts ...grpc.CallOption) (*Profile, error)
	/// ProfileService UpdateProfile :- help's us to update the profile
	UpdateProfile(ctx context.Context, in *Profile, opts ...grpc.CallOption) (*protobuf.Id, error)
	/// ProfileService  ValidateUsername :- help's us to validate username
	/// availability
	ValidateUsername(ctx context.Context, in *ValidateUsernameRequest, opts ...grpc.CallOption) (*protobuf.DefaultResponse, error)
	/// ProfileService ValidateEmail :- help's us to validate email availability
	ValidateEmail(ctx context.Context, in *ValidateEmailRequest, opts ...grpc.CallOption) (*protobuf.DefaultResponse, error)
	/// Used to check health status of the running microservice
	Check(ctx context.Context, in *protobuf.HealthCheckRequest, opts ...grpc.CallOption) (*protobuf.HealthCheckResponse, error)
	/// Used to check health status of the running microservice as stream
	Watch(ctx context.Context, in *protobuf.HealthCheckRequest, opts ...grpc.CallOption) (ProfileService_WatchClient, error)
}

type profileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProfileServiceClient(cc grpc.ClientConnInterface) ProfileServiceClient {
	return &profileServiceClient{cc}
}

func (c *profileServiceClient) Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/profile.ProfileService/Auth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) RefreshToken(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/profile.ProfileService/RefreshToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) VerifyToken(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*AccessDetails, error) {
	out := new(AccessDetails)
	err := c.cc.Invoke(ctx, "/profile.ProfileService/VerifyToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) Logout(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*protobuf.DefaultResponse, error) {
	out := new(protobuf.DefaultResponse)
	err := c.cc.Invoke(ctx, "/profile.ProfileService/Logout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) CreateProfile(ctx context.Context, in *Profile, opts ...grpc.CallOption) (*protobuf.Id, error) {
	out := new(protobuf.Id)
	err := c.cc.Invoke(ctx, "/profile.ProfileService/CreateProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) ConfirmProfile(ctx context.Context, in *ConfirmProfileRequest, opts ...grpc.CallOption) (*protobuf.DefaultResponse, error) {
	out := new(protobuf.DefaultResponse)
	err := c.cc.Invoke(ctx, "/profile.ProfileService/ConfirmProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) ReadProfile(ctx context.Context, in *ReadProfileRequest, opts ...grpc.CallOption) (*Profile, error) {
	out := new(Profile)
	err := c.cc.Invoke(ctx, "/profile.ProfileService/ReadProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) UpdateProfile(ctx context.Context, in *Profile, opts ...grpc.CallOption) (*protobuf.Id, error) {
	out := new(protobuf.Id)
	err := c.cc.Invoke(ctx, "/profile.ProfileService/UpdateProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) ValidateUsername(ctx context.Context, in *ValidateUsernameRequest, opts ...grpc.CallOption) (*protobuf.DefaultResponse, error) {
	out := new(protobuf.DefaultResponse)
	err := c.cc.Invoke(ctx, "/profile.ProfileService/ValidateUsername", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) ValidateEmail(ctx context.Context, in *ValidateEmailRequest, opts ...grpc.CallOption) (*protobuf.DefaultResponse, error) {
	out := new(protobuf.DefaultResponse)
	err := c.cc.Invoke(ctx, "/profile.ProfileService/ValidateEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) Check(ctx context.Context, in *protobuf.HealthCheckRequest, opts ...grpc.CallOption) (*protobuf.HealthCheckResponse, error) {
	out := new(protobuf.HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/profile.ProfileService/Check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) Watch(ctx context.Context, in *protobuf.HealthCheckRequest, opts ...grpc.CallOption) (ProfileService_WatchClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ProfileService_serviceDesc.Streams[0], "/profile.ProfileService/Watch", opts...)
	if err != nil {
		return nil, err
	}
	x := &profileServiceWatchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ProfileService_WatchClient interface {
	Recv() (*protobuf.HealthCheckResponse, error)
	grpc.ClientStream
}

type profileServiceWatchClient struct {
	grpc.ClientStream
}

func (x *profileServiceWatchClient) Recv() (*protobuf.HealthCheckResponse, error) {
	m := new(protobuf.HealthCheckResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ProfileServiceServer is the server API for ProfileService service.
type ProfileServiceServer interface {
	/// ProfileService Auth for authentication
	Auth(context.Context, *AuthRequest) (*AuthResponse, error)
	/// ProfileService RefreshToken for fetching new refresh token
	RefreshToken(context.Context, *TokenRequest) (*AuthResponse, error)
	/// ProfileService VerifyToken help's us to verify the auth token and return
	/// us back the profile data
	VerifyToken(context.Context, *TokenRequest) (*AccessDetails, error)
	/// ProfileService Logout help's us to remove all the data associated with the
	/// user session
	Logout(context.Context, *TokenRequest) (*protobuf.DefaultResponse, error)
	/// ProfileService CreateProfile :- help's uo to create a profile
	CreateProfile(context.Context, *Profile) (*protobuf.Id, error)
	/// ProfileService ConfirmProfile :- help's us to verify the profile
	ConfirmProfile(context.Context, *ConfirmProfileRequest) (*protobuf.DefaultResponse, error)
	/// ProfileService ReadProfile :- help's us to read the entire profile data
	ReadProfile(context.Context, *ReadProfileRequest) (*Profile, error)
	/// ProfileService UpdateProfile :- help's us to update the profile
	UpdateProfile(context.Context, *Profile) (*protobuf.Id, error)
	/// ProfileService  ValidateUsername :- help's us to validate username
	/// availability
	ValidateUsername(context.Context, *ValidateUsernameRequest) (*protobuf.DefaultResponse, error)
	/// ProfileService ValidateEmail :- help's us to validate email availability
	ValidateEmail(context.Context, *ValidateEmailRequest) (*protobuf.DefaultResponse, error)
	/// Used to check health status of the running microservice
	Check(context.Context, *protobuf.HealthCheckRequest) (*protobuf.HealthCheckResponse, error)
	/// Used to check health status of the running microservice as stream
	Watch(*protobuf.HealthCheckRequest, ProfileService_WatchServer) error
}

// UnimplementedProfileServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProfileServiceServer struct {
}

func (*UnimplementedProfileServiceServer) Auth(ctx context.Context, req *AuthRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Auth not implemented")
}
func (*UnimplementedProfileServiceServer) RefreshToken(ctx context.Context, req *TokenRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshToken not implemented")
}
func (*UnimplementedProfileServiceServer) VerifyToken(ctx context.Context, req *TokenRequest) (*AccessDetails, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyToken not implemented")
}
func (*UnimplementedProfileServiceServer) Logout(ctx context.Context, req *TokenRequest) (*protobuf.DefaultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}
func (*UnimplementedProfileServiceServer) CreateProfile(ctx context.Context, req *Profile) (*protobuf.Id, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProfile not implemented")
}
func (*UnimplementedProfileServiceServer) ConfirmProfile(ctx context.Context, req *ConfirmProfileRequest) (*protobuf.DefaultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmProfile not implemented")
}
func (*UnimplementedProfileServiceServer) ReadProfile(ctx context.Context, req *ReadProfileRequest) (*Profile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadProfile not implemented")
}
func (*UnimplementedProfileServiceServer) UpdateProfile(ctx context.Context, req *Profile) (*protobuf.Id, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProfile not implemented")
}
func (*UnimplementedProfileServiceServer) ValidateUsername(ctx context.Context, req *ValidateUsernameRequest) (*protobuf.DefaultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateUsername not implemented")
}
func (*UnimplementedProfileServiceServer) ValidateEmail(ctx context.Context, req *ValidateEmailRequest) (*protobuf.DefaultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateEmail not implemented")
}
func (*UnimplementedProfileServiceServer) Check(ctx context.Context, req *protobuf.HealthCheckRequest) (*protobuf.HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (*UnimplementedProfileServiceServer) Watch(req *protobuf.HealthCheckRequest, srv ProfileService_WatchServer) error {
	return status.Errorf(codes.Unimplemented, "method Watch not implemented")
}

func RegisterProfileServiceServer(s *grpc.Server, srv ProfileServiceServer) {
	s.RegisterService(&_ProfileService_serviceDesc, srv)
}

func _ProfileService_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.ProfileService/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).Auth(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.ProfileService/RefreshToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).RefreshToken(ctx, req.(*TokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_VerifyToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).VerifyToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.ProfileService/VerifyToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).VerifyToken(ctx, req.(*TokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.ProfileService/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).Logout(ctx, req.(*TokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_CreateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Profile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).CreateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.ProfileService/CreateProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).CreateProfile(ctx, req.(*Profile))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_ConfirmProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).ConfirmProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.ProfileService/ConfirmProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).ConfirmProfile(ctx, req.(*ConfirmProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_ReadProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).ReadProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.ProfileService/ReadProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).ReadProfile(ctx, req.(*ReadProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Profile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.ProfileService/UpdateProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).UpdateProfile(ctx, req.(*Profile))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_ValidateUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateUsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).ValidateUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.ProfileService/ValidateUsername",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).ValidateUsername(ctx, req.(*ValidateUsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_ValidateEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).ValidateEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.ProfileService/ValidateEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).ValidateEmail(ctx, req.(*ValidateEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(protobuf.HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.ProfileService/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).Check(ctx, req.(*protobuf.HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(protobuf.HealthCheckRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProfileServiceServer).Watch(m, &profileServiceWatchServer{stream})
}

type ProfileService_WatchServer interface {
	Send(*protobuf.HealthCheckResponse) error
	grpc.ServerStream
}

type profileServiceWatchServer struct {
	grpc.ServerStream
}

func (x *profileServiceWatchServer) Send(m *protobuf.HealthCheckResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _ProfileService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "profile.ProfileService",
	HandlerType: (*ProfileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Auth",
			Handler:    _ProfileService_Auth_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _ProfileService_RefreshToken_Handler,
		},
		{
			MethodName: "VerifyToken",
			Handler:    _ProfileService_VerifyToken_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _ProfileService_Logout_Handler,
		},
		{
			MethodName: "CreateProfile",
			Handler:    _ProfileService_CreateProfile_Handler,
		},
		{
			MethodName: "ConfirmProfile",
			Handler:    _ProfileService_ConfirmProfile_Handler,
		},
		{
			MethodName: "ReadProfile",
			Handler:    _ProfileService_ReadProfile_Handler,
		},
		{
			MethodName: "UpdateProfile",
			Handler:    _ProfileService_UpdateProfile_Handler,
		},
		{
			MethodName: "ValidateUsername",
			Handler:    _ProfileService_ValidateUsername_Handler,
		},
		{
			MethodName: "ValidateEmail",
			Handler:    _ProfileService_ValidateEmail_Handler,
		},
		{
			MethodName: "Check",
			Handler:    _ProfileService_Check_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _ProfileService_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "services/profile/service.proto",
}
